[project]
name = "shot-database"
version = "0.1.0"
description = "Python scripts to generate shot database metadata"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-genai>=1.53.0",
    "pillow>=12.0.0",
    "python-dotenv>=1.2.1",
]
